// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: src/proto/api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayMultipleHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayMultipleHelloClient, error)
	SayHelloToMultiplePeople(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloToMultiplePeopleClient, error)
	SayHelloToEachPerson(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloToEachPersonClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc_api.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayMultipleHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayMultipleHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/grpc_api.Greeter/SayMultipleHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayMultipleHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayMultipleHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayMultipleHelloClient struct {
	grpc.ClientStream
}

func (x *greeterSayMultipleHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloToMultiplePeople(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloToMultiplePeopleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/grpc_api.Greeter/SayHelloToMultiplePeople", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloToMultiplePeopleClient{stream}
	return x, nil
}

type Greeter_SayHelloToMultiplePeopleClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloToMultiplePeopleClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloToMultiplePeopleClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloToMultiplePeopleClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloToEachPerson(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloToEachPersonClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/grpc_api.Greeter/SayHelloToEachPerson", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloToEachPersonClient{stream}
	return x, nil
}

type Greeter_SayHelloToEachPersonClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloToEachPersonClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloToEachPersonClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloToEachPersonClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayMultipleHello(*HelloRequest, Greeter_SayMultipleHelloServer) error
	SayHelloToMultiplePeople(Greeter_SayHelloToMultiplePeopleServer) error
	SayHelloToEachPerson(Greeter_SayHelloToEachPersonServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SayMultipleHello(*HelloRequest, Greeter_SayMultipleHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method SayMultipleHello not implemented")
}
func (UnimplementedGreeterServer) SayHelloToMultiplePeople(Greeter_SayHelloToMultiplePeopleServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloToMultiplePeople not implemented")
}
func (UnimplementedGreeterServer) SayHelloToEachPerson(Greeter_SayHelloToEachPersonServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloToEachPerson not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayMultipleHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayMultipleHello(m, &greeterSayMultipleHelloServer{stream})
}

type Greeter_SayMultipleHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayMultipleHelloServer struct {
	grpc.ServerStream
}

func (x *greeterSayMultipleHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHelloToMultiplePeople_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloToMultiplePeople(&greeterSayHelloToMultiplePeopleServer{stream})
}

type Greeter_SayHelloToMultiplePeopleServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloToMultiplePeopleServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloToMultiplePeopleServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloToMultiplePeopleServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_SayHelloToEachPerson_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloToEachPerson(&greeterSayHelloToEachPersonServer{stream})
}

type Greeter_SayHelloToEachPersonServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloToEachPersonServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloToEachPersonServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloToEachPersonServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayMultipleHello",
			Handler:       _Greeter_SayMultipleHello_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloToMultiplePeople",
			Handler:       _Greeter_SayHelloToMultiplePeople_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloToEachPerson",
			Handler:       _Greeter_SayHelloToEachPerson_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/api.proto",
}
